/*
 *  Licensed to the Apache Software Foundation (ASF) under one
 *  or more contributor license agreements.  See the NOTICE file
 *  distributed with this work for additional information
 *  regarding copyright ownership.  The ASF licenses this file
 *  to you under the Apache License, Version 2.0 (the
 *  "License"); you may not use this file except in compliance
 *  with the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an
 *  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 *  KIND, either express or implied.  See the License for the
 *  specific language governing permissions and limitations
 *  under the License.
 *
 */

/*
 *                        AT&T - PROPRIETARY
 *          THIS FILE CONTAINS PROPRIETARY INFORMATION OF
 *        AT&T AND IS NOT TO BE DISCLOSED OR USED EXCEPT IN
 *             ACCORDANCE WITH APPLICABLE AGREEMENTS.
 *
 *          Copyright (c) 2014 AT&T Knowledge Ventures
 *              Unpublished and Not for Publication
 *                     All Rights Reserved
 */
package org.apache.openaz.xacml.api.pap;

import java.util.Properties;
import java.util.Set;

public interface PDPGroup {

    /*
     * The ID is a string that is unique within the current set of groups. It is generated by the code. It is
     * distinct from the name in that the ID must be able to be a directory name and a key in a properties
     * file. The ID does not need to be unique forever. It just needs to distinguish this group from other
     * groups that currently exist.
     */
    String getId();

    boolean isDefaultGroup();

    /*
     * The name is a free-form string that is user input.
     */
    String getName();

    void setName(String name);

    String getDescription();

    void setDescription(String description);

    PDPGroupStatus getStatus();

    Set<PDP> getPdps();

    Set<PDPPolicy> getPolicies();

    PDPPolicy getPolicy(String id);

    Properties getPolicyProperties();

    Set<PDPPIPConfig> getPipConfigs();

    PDPPIPConfig getPipConfig(String id);

    Properties getPipConfigProperties();

    void repair();

}
